[package]
name = "nvidia-deepstream-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gstreamer = "0.19.4"
nvidia-deepstream = { version = "0.1.0", path = "../nvidia-deepstream" }
